### ISSUE TITLE
Deprecation notice: "Implicit conversion from float to int loses precision" on upgrade to PHP 8.1

### ISSUE THREAD

**Issue by matt-harvey** [hidehalo/nanoid-php#16]
## Detailed description

Firstly, thanks for this great package :)

The issue:

After upgrading from PHP 8.0 to PHP 8.1, I receive the deprecation notice described in the title when trying to use this library to generate a nanoid.

Minimal code to reproduce:

```php
use Hidehalo\Nanoid\Client;

$client = new Client();
$client->generateId(21, Client::MODE_DYNAMIC);
```

Logged:

```
[errno: 8192] Implicit conversion from float 5.977279923499917 to int loses precision
```

## Context

I used this library to generate unique IDs for various entities.

## Possible implementation

Explicitly converting to an `int` should fix this deprecation notice. The relevant code is in src/Core.php on line 13.

## Your environment

PHP 8.1.0 running on local development server with `php -s`. Version of this library as described in `composer.lock` is:

```
            "name": "hidehalo/nanoid-php",
            "version": "1.1.8",
            "source": {
                "type": "git",
                "url": "https://github.com/hidehalo/nanoid-php.git",
                "reference": "14187ab7a5affa34078b6a54df94176bb7a21227"
            },
```

**Comment by hidehalo** [comment]
Nice report!

**Comment by matt-harvey** [comment]
Thanks @hidehalo . But why the 'wontfix' label? I've pushed a PR to fix it already.

**Comment by hidehalo** [comment]
> Thanks @hidehalo . But why the 'wontfix' label? I've pushed a PR to fix it already.

🤣 It's a mistake...

**Comment by matt-harvey** [comment]
Haha OK, no worries :)

**Comment by hidehalo** [comment]
> > Thanks @hidehalo . But why the 'wontfix' label? I've pushed a PR to fix it already.
> 
> 🤣 It's a mistake...

XD
