### ISSUE TITLE
generateID should use Client settings as default

### ISSUE THREAD

**Issue by splitbrain** [hidehalo/nanoid-php#3]
The Client is initialized with a size and a generator:

```php
public function __construct($size = 21, GeneratorInterface $generator = null)
```

However when using the client, the size is mandatory to specify:

```php
public function generateId($size, $mode = self::MODE_NORMAL)
```

It would make more sense to me if the `$size` parameter would be optional for `generateId` and default to whatever was specified in the client constructor.

**Comment by hidehalo** [comment]
@splitbrain great idea, could you review the new PR for it?

**Comment by splitbrain** [comment]
Looks good to me. I wouldn't even consider this a breaking change. People can still pass their own size just as before.

**Comment by hidehalo** [comment]
@splitbrain thank you
